// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0e1HTvZYDARg4mwEn3_LULi3RvH3e97s',
    appId: '1:127192656255:web:576b016736d407eaf8d24a',
    messagingSenderId: '127192656255',
    projectId: 'sproutly-7e69f',
    authDomain: 'sproutly-7e69f.firebaseapp.com',
    storageBucket: 'sproutly-7e69f.firebasestorage.app',
    measurementId: 'G-S9PTDW3EY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClMGC2eTqX2Fwm-xIw8qg-WtUl0LkRAzs',
    appId: '1:127192656255:android:6d3b9462e09fd187f8d24a',
    messagingSenderId: '127192656255',
    projectId: 'sproutly-7e69f',
    storageBucket: 'sproutly-7e69f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UEJP-2prrp-21lmx6T0dW5jzcPOeYN4',
    appId: '1:127192656255:ios:fdfca73cbb1dc3d1f8d24a',
    messagingSenderId: '127192656255',
    projectId: 'sproutly-7e69f',
    storageBucket: 'sproutly-7e69f.firebasestorage.app',
    iosBundleId: 'com.example.sproutly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UEJP-2prrp-21lmx6T0dW5jzcPOeYN4',
    appId: '1:127192656255:ios:fdfca73cbb1dc3d1f8d24a',
    messagingSenderId: '127192656255',
    projectId: 'sproutly-7e69f',
    storageBucket: 'sproutly-7e69f.firebasestorage.app',
    iosBundleId: 'com.example.sproutly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0e1HTvZYDARg4mwEn3_LULi3RvH3e97s',
    appId: '1:127192656255:web:c8b278ca922d3af4f8d24a',
    messagingSenderId: '127192656255',
    projectId: 'sproutly-7e69f',
    authDomain: 'sproutly-7e69f.firebaseapp.com',
    storageBucket: 'sproutly-7e69f.firebasestorage.app',
    measurementId: 'G-DE4KNRBGCR',
  );
}
